[package]
name = "mindustry_logic_bang_lang"
version = "0.3.0"
edition = "2021"

authors = ["A4-Tacks <wdsjxhno1001@163.com>"]
description = "一个偏向底层的用于Mindustry游戏中逻辑处理器的语言"
categories = ["command-line-utilities"]
keywords = ["compiler", "lang", "mindustry"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.20.0"


[dependencies]
[dependencies.lalrpop-util]
version = "0.20.0"

features = [
    "unicode",
    "regex",
    "lexer"
]

[profile.release]
strip = true
lto = true
