[package]
name = "display_source"
version = "0.3.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syntax = { path = "../syntax", version = "*" }

[dev-dependencies]
parser = { path = "../parser", version = "*" }
