#!/usr/bin/bash
set -o nounset
set -o errtrace
function catch_error {
    local LEC=$? name i line file
    echo "Traceback (most recent call last):" >&2
    for ((i = ${#FUNCNAME[@]} - 1; i >= 0; --i)); do
        name="${FUNCNAME[$i]}"
        line="${BASH_LINENO[$i]}"
        file="${BASH_SOURCE[$i]}"
        echo "  File ${file@Q}, line ${line}, in ${name@Q}" >&2
    done
    echo "Error: [ExitCode: ${LEC}]" >&2
    exit "${LEC}"
}
trap catch_error ERR

[ $# -le 1 ]

COMPILE_TARGET="${1-aarch64-unknown-linux-musl}"

TARGET_DIR="target/${COMPILE_TARGET}/"
NAME=mindustry_logic_bang_lang

cargo build --release --target="${COMPILE_TARGET}"

test -d "${TARGET_DIR}"

cd "${TARGET_DIR}/release/" || exit

test -f "${NAME}" \
    && test -r "${NAME}" \
    && test -x "${NAME}"

TARPKG_NAME="${NAME}.tar"
XZPKG_NAME="${TARPKG_NAME}.xz"
[ -f "${TARPKG_NAME}" ] && rm "${TARPKG_NAME}"
[ -f "${XZPKG_NAME}" ] && rm "${XZPKG_NAME}"

tar -cf "${TARPKG_NAME}" "${NAME}"
xz -k9evvT1 "${TARPKG_NAME}"

HASHER=sha256sum
HASHER_NAME="${HASHER##*/}"
HASH_OUT="$("${HASHER}" "${XZPKG_NAME}")"
HASH_CODE="${HASH_OUT%% *}"
HASH_CODE_FILE="${XZPKG_NAME}.${HASHER_NAME}"
echo "${HASH_CODE}" > "${HASH_CODE_FILE}"
